on:
  schedule:
  - cron: "0 12 1 * *"
  - cron: "0 12 15 * *"
  workflow_dispatch:

name: Download dos arquivos HTML

jobs:
  render:
    name: Download dos arquivos HTML
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - name: Install remotes and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
        shell: Rscript {0}
      - name: Execute script
        run: |
          Rscript -e 'source("inst/script_download_arquivos.R")'
          Rscript -e 'source("inst/actions_download_agenda_mais_informacoes.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all inst/
          git commit -m 'Download das páginas em HTML' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
